### ISSUE TITLE
Improve paper layout

### ISSUE THREAD

**Issue by EntilZha** [acl-org/acl-2023-miniconf#15]
Currently paper papers are vertically stacked (paper info, then chat channel, then poster, etc). It would be great to improve this so that chat is to the right side and content of the left side.

**Comment by EntilZha** [comment]
A configurable width view would be great. Something like/equivalent to either:
- Default split view with reasonable ratio
- Content only view
- Chat only view.

**Comment by koustuvsinha** [comment]
@EntilZha added it, can you check?
