### ISSUE TITLE
Add Room Information to Paper Pages

### ISSUE THREAD

**Issue by EntilZha** [acl-org/acl-2023-miniconf#23]
Room information is missing from the paper pages. It should be added as shown in the screenshot below, on its own line.
![image](https://github.com/acl-org/acl-2023-miniconf/assets/1382460/794072c8-931d-4f05-94ae-c8e922e8ade0)

**Comment by houyu0930** [comment]
Hi Pedro, for conference room information, I plan to display smth like `Conference Room: Metropolitan East` for oral ones. However, I noticed for posters, the room info becomes `Conference Room: Poster Session` or `Conference Room: Virtual Poster Session`. Do we want to display this? Thanks!
