### ISSUE TITLE
Missing conference room info for posters

### ISSUE THREAD

**Issue by houyu0930** [acl-org/acl-2023-miniconf#41]
Context: #23 

Currently we use `Poster Session` and `Virtual Poster Session` as the room info for posters. It would be great if we could update later with the room names.

**Comment by EntilZha** [comment]
This should be fixed actually. If you're adding room information soon, be sure to update to the most recent master

**Comment by houyu0930** [comment]
Got it! Just checked again. Thanks Pedro for the update!
