### ISSUE TITLE
Issue on Virtual Site

### ISSUE THREAD

**Issue by todpole3** [acl-org/acl-2023-miniconf#88]
- [ ] My issue is about my paper on MiniConf
- [ x] My issue is about logging into RocketChat
- [ ] My issue is something different, but not on the list of things we cannot help with.

## RocketChat Login Issues

- [ ] I confirm that I am registered for the conference on Underline and can login at https://underline.io/events/395/reception
- Did you login by pressing "Login with Underline" or some other way: I registered for 1-day tutorial. I tried to register at https://underline.io/events/395/reception and the purple "Register" button is not working. I cannot login to any of the tutorial session or chats.
- What is your Underline email: xilin@cs.washington.edu

**Comment by villalbamartin** [comment]
Hi,

is it possible that you registered today for the conference?

**Comment by EntilZha** [comment]
@villalbamartin Resolved this issue, we both work at Meta so was easier to take offline :)
